"""Problem N_5_B_example specification (generated by netl_triga_fuel_loader).

Edit the fuel material definitions and the fuel loading below, then run this
problem's setup.py to regenerate the MPACT / OpenMC input.
"""

import openmc

from progression_problems.TRIGA.default_geometries import FuelSpec
from progression_problems.TRIGA.default_materials import DefaultMaterials
from progression_problems.TRIGA.NETL.default_geometries import DefaultGeometries as NETLDefaultGeometries


problem_ID = 'N_5_B_example'


def _build_fuel(name, density, density_units, temperature, percent_type, nuclides, elements, s_alpha_beta):
    material = openmc.Material(name=name)
    material.temperature = temperature
    material.set_density(density_units, density)
    for nuclide, fraction in nuclides.items():
        material.add_nuclide(nuclide, fraction, percent_type=percent_type)
    for element, fraction in elements.items():
        material.add_element(element, fraction, percent_type=percent_type)
    for law in s_alpha_beta:
        material.add_s_alpha_beta(law)
    return material


# --- Fuel material definitions (edit here) ---

Fuel_Hot = _build_fuel(
    name='Fuel_Hot',
    density=5.85,
    density_units='g/cm3',
    temperature=800.0,
    percent_type='wo',
    nuclides={
        'H1': 0.014355,
        'Mn55': 0.0014287,
        'U235': 0.0152,
        'U238': 0.061568,
        'Zr90': 0.43706,
        'Zr91': 0.0942,
        'Zr92': 0.14253,
        'Zr94': 0.14136,
        'Zr96': 0.02228,
    },
    elements={
        'Cr': 0.013573,
        'Fe': 0.049647,
        'Ni': 0.0067863,
    },
    s_alpha_beta=['c_H_in_ZrH', 'c_Zr_in_ZrH'],
)

Fuel_Warm = _build_fuel(
    name='Fuel_Warm',
    density=5.85,
    density_units='g/cm3',
    temperature=700.0,
    percent_type='wo',
    nuclides={
        'H1': 0.014355,
        'Mn55': 0.0014287,
        'U235': 0.0152,
        'U238': 0.061568,
        'Zr90': 0.43706,
        'Zr91': 0.0942,
        'Zr92': 0.14253,
        'Zr94': 0.14136,
        'Zr96': 0.02228,
    },
    elements={
        'Cr': 0.013573,
        'Fe': 0.049647,
        'Ni': 0.0067863,
    },
    s_alpha_beta=['c_H_in_ZrH', 'c_Zr_in_ZrH'],
)


# --- Fuel loading (core location -> fuel material) ---
fuel_materials = {
    'B-01': FuelSpec(material=Fuel_Hot),
    'B-02': FuelSpec(material=Fuel_Hot),
    'B-03': FuelSpec(material=Fuel_Hot),
    'B-04': FuelSpec(material=Fuel_Hot),
    'B-05': FuelSpec(material=Fuel_Hot),
    'B-06': FuelSpec(material=Fuel_Hot),
    'C-02': FuelSpec(material=Fuel_Warm),
    'C-03': FuelSpec(material=Fuel_Warm),
    'C-04': FuelSpec(material=Fuel_Warm),
    'C-05': FuelSpec(material=Fuel_Warm),
    'C-06': FuelSpec(material=Fuel_Warm),
}


coolant = DefaultMaterials.water(
    temperature=293.15,
    density=0.997,
    density_units='g/cm3',
)

reactor = NETLDefaultGeometries.reactor(
    fuel_temp=600.0,
    non_fuel_temp=293.15,
    coolant=coolant,
    fuel_materials=fuel_materials,
    transient_rod_position=NETLDefaultGeometries.TRANSIENT_ROD_FULLY_INSERTED_POSITION,
    regulating_rod_position=NETLDefaultGeometries.FFCR_FULLY_INSERTED_POSITION,
    shim_1_rod_position=NETLDefaultGeometries.FFCR_FULLY_INSERTED_POSITION,
    shim_2_rod_position=NETLDefaultGeometries.FFCR_FULLY_INSERTED_POSITION,
)
