"""Generate a runnable ``specs.py`` from a :class:`CoreLoadingPattern`.

The generated file is **self-contained**: it depends only on ``openmc`` and
``progression_problems`` (not on this package), builds each fuel material with an
inline helper so the compositions are visible and editable in the input file, and
calls ``NETLDefaultGeometries.reactor(..., fuel_materials=...)`` to place the
per-location fuel. Output is deterministic for a given pattern/config so
regenerated files diff cleanly.

This module is dependency-light (pure string generation -- no OpenMC needed to
generate); OpenMC/CoreForge are only needed to *run* the generated ``specs.py``.
"""

from __future__ import annotations

import keyword
import re
import shutil
from dataclasses import dataclass
from pathlib import Path
from typing import Dict, List, Union

from netl_triga_fuel_loader.loading import CoreLoadingPattern
from netl_triga_fuel_loader.materials import FuelMaterialSpec

# Emitted for a rod position left as ``None`` (i.e. use the fully-inserted default).
_TRANSIENT_ROD_DEFAULT = "NETLDefaultGeometries.TRANSIENT_ROD_FULLY_INSERTED_POSITION"
_FFCR_ROD_DEFAULT = "NETLDefaultGeometries.FFCR_FULLY_INSERTED_POSITION"


@dataclass
class SpecsConfig:
    """Reactor/problem parameters for the generated ``specs.py``.

    Only fuel placement comes from the :class:`CoreLoadingPattern`; these are the
    remaining ``reactor(...)`` arguments. Rod positions left as ``None`` are emitted
    as the fully-inserted default constants.
    """

    problem_id: str
    fuel_temp: float = 600.0
    non_fuel_temp: float = 293.15
    coolant_temperature: float = 293.15
    coolant_density: float = 0.9970
    coolant_density_units: str = "g/cm3"
    transient_rod_position: Union[float, None] = None
    regulating_rod_position: Union[float, None] = None
    shim_1_rod_position: Union[float, None] = None
    shim_2_rod_position: Union[float, None] = None

    def __post_init__(self) -> None:
        if not self.problem_id or not self.problem_id.strip():
            raise ValueError("SpecsConfig.problem_id must be a non-empty string.")


def _identifier(name: str, used: set) -> str:
    """A unique, valid Python identifier derived from a fuel-group name."""
    base = re.sub(r"\W", "_", name)
    if not base or base[0].isdigit():
        base = f"fuel_{base}"
    if keyword.iskeyword(base):
        base = f"{base}_"
    candidate, index = base, 2
    while candidate in used:
        candidate = f"{base}_{index}"
        index += 1
    used.add(candidate)
    return candidate


def _rod_position(value: Union[float, None], default_reference: str) -> str:
    """Emit a rod position as a literal float or the fully-inserted default constant."""
    return default_reference if value is None else repr(float(value))


def _emit_fuel_material(variable: str, spec: FuelMaterialSpec) -> List[str]:
    """Lines defining one fuel material via the inline ``_build_fuel`` helper."""
    lines = [
        f"{variable} = _build_fuel(",
        f"    name={spec.name!r},",
        f"    density={spec.density!r},",
        f"    density_units={spec.density_units!r},",
        f"    temperature={spec.temperature!r},",
        f"    percent_type={spec.percent_type!r},",
        "    nuclides={",
    ]
    lines += [f"        {nuclide!r}: {fraction!r}," for nuclide, fraction in spec.nuclides.items()]
    lines.append("    },")
    lines.append("    elements={")
    lines += [f"        {element!r}: {fraction!r}," for element, fraction in spec.elements.items()]
    lines.append("    },")
    lines.append(f"    s_alpha_beta={list(spec.s_alpha_beta)!r},")
    lines.append(")")
    return lines


_HEADER_TEMPLATE = '''"""Problem {problem_id} specification (generated by netl_triga_fuel_loader).

Edit the fuel material definitions and the fuel loading below, then run this
problem's setup.py to regenerate the MPACT / OpenMC input.
"""

import openmc

from progression_problems.TRIGA.default_geometries import FuelSpec
from progression_problems.TRIGA.default_materials import DefaultMaterials
from progression_problems.TRIGA.NETL.default_geometries import DefaultGeometries as NETLDefaultGeometries


problem_ID = {problem_id!r}


def _build_fuel(name, density, density_units, temperature, percent_type, nuclides, elements, s_alpha_beta):
    material = openmc.Material(name=name)
    material.temperature = temperature
    material.set_density(density_units, density)
    for nuclide, fraction in nuclides.items():
        material.add_nuclide(nuclide, fraction, percent_type=percent_type)
    for element, fraction in elements.items():
        material.add_element(element, fraction, percent_type=percent_type)
    for law in s_alpha_beta:
        material.add_s_alpha_beta(law)
    return material
'''


def render_specs(pattern: CoreLoadingPattern, config: SpecsConfig) -> str:
    """Render a runnable ``specs.py`` (as a string) for ``pattern`` and ``config``.

    Deterministic: the same pattern/config always produces identical text.
    """
    pattern.validate()

    # Only groups actually placed somewhere need a definition; emit them by name.
    used_groups = sorted(set(pattern.assignments.values()))
    group_variables: Dict[str, str] = {}
    used_identifiers: set = set()
    for group_name in used_groups:
        group_variables[group_name] = _identifier(group_name, used_identifiers)

    lines: List[str] = [_HEADER_TEMPLATE.format(problem_id=config.problem_id)]

    lines.append("")
    lines.append("# --- Fuel material definitions (edit here) ---")
    for group_name in used_groups:
        lines.append("")
        lines += _emit_fuel_material(group_variables[group_name], pattern.groups[group_name])

    lines.append("")
    lines.append("")
    lines.append("# --- Fuel loading (core location -> fuel material) ---")
    lines.append("fuel_materials = {")
    for location in sorted(pattern.assignments):
        variable = group_variables[pattern.assignments[location]]
        lines.append(f"    {location!r}: FuelSpec(material={variable}),")
    lines.append("}")

    lines.append("")
    lines.append("")
    lines.append("coolant = DefaultMaterials.water(")
    lines.append(f"    temperature={config.coolant_temperature!r},")
    lines.append(f"    density={config.coolant_density!r},")
    lines.append(f"    density_units={config.coolant_density_units!r},")
    lines.append(")")

    lines.append("")
    lines.append("reactor = NETLDefaultGeometries.reactor(")
    lines.append(f"    fuel_temp={config.fuel_temp!r},")
    lines.append(f"    non_fuel_temp={config.non_fuel_temp!r},")
    lines.append("    coolant=coolant,")
    lines.append("    fuel_materials=fuel_materials,")
    lines.append(f"    transient_rod_position={_rod_position(config.transient_rod_position, _TRANSIENT_ROD_DEFAULT)},")
    lines.append(f"    regulating_rod_position={_rod_position(config.regulating_rod_position, _FFCR_ROD_DEFAULT)},")
    lines.append(f"    shim_1_rod_position={_rod_position(config.shim_1_rod_position, _FFCR_ROD_DEFAULT)},")
    lines.append(f"    shim_2_rod_position={_rod_position(config.shim_2_rod_position, _FFCR_ROD_DEFAULT)},")
    lines.append(")")

    return "\n".join(lines) + "\n"


def write_specs(
    pattern: CoreLoadingPattern,
    config: SpecsConfig,
    path: Union[str, Path],
    *,
    overwrite: bool = False,
    backup: bool = True,
) -> Path:
    """Write the generated ``specs.py`` to ``path``.

    Guards against clobbering: if ``path`` exists, raises ``FileExistsError`` unless
    ``overwrite=True``; when overwriting, the previous file is copied to
    ``<path>.bak`` first (unless ``backup=False``).
    """
    path = Path(path)
    if path.exists():
        if not overwrite:
            raise FileExistsError(f"{path} already exists; pass overwrite=True to replace it.")
        if backup:
            shutil.copy2(path, path.with_suffix(path.suffix + ".bak"))
    path.write_text(render_specs(pattern, config))
    return path
